import {Size} from './jsgui.mts';

export function generateFontSizeCssVars(names: string[] = Object.values(Size)) {
  type SizeDef = {
    fontSize: number;
    iconSize: number;
    size: number;
  };
  const getSizeDef = (i: number) => ({
    size: 19 + i*4,
    iconSize: 14 + i*4,
    fontSize: 14 + i*4,
  }) as SizeDef;
  let acc = "  /* generated by generateFontSizeCssVars */";
  for (let i = 0; i < names.length; i++) {
    const name = names[i];
    const {size, fontSize, iconSize} = getSizeDef(i);
    acc += `\n  --size-${name}: ${size}px;`;
    acc += `\n  --iconSize-${name}: ${iconSize}px;`;
    acc += `\n  --fontSize-${name}: ${fontSize}px;`;
  }
  return acc;
}
setTimeout(() => {
  //console.log(generateFontSizeCssVars());
})
